name: 'Create a pull request'

runs:
  using: composite
  steps:
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        run: |
          gh pr create --base main --head dev --title "New Feature" --body "This is a new pull request"
        env:
          GH_TOKEN: ${{ secrets.CREATEPULLREQUEST }}                             # You will get: "message": "Bad credentials" unless you use a personal access token with at least repo scope.
