name: GitHub CLI Token Login Demo

on:
  push

jobs:
  gh-login:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
# -H "Authorization: token ${{ secrets.CREATEPULLREQUEST }}" \

      - name: Create Pull Request
        run: |
          curl -X POST \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{
                  "title": "Merge changes from dev to main",
                  "body": "This PR merges the latest changes from the dev branch into the main branch.",
                  "head": "dev",
                  "base": "main"
                }'
