name: GitHub CLI  Token Login Demo

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  gh-login:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                                       
      - name: Create Pull Request                                                        # You will get: "message": "Bad credentials" unless you use a personal access token with at least repo scope.
        run: |
          curl -X POST \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -H "Authorization: token ${{ secrets.CREATEPULLREQUEST }}" \
            -d '{
                  "title": "Merge changes from dev to main",
                  "body": "This PR merges the latest changes from the dev branch into the main branch.",
                  "head": "dev",
                  "base": "main"
                }'
