name: GitHub CLI  Token Login Demo

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  gh-login:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
                                       
      - name: Create Pull Request                                                        # You will get: "message": "Bad credentials" unless you use a personal access token with at least repo scope.
        run: |
          gh pr create --base main --head feature-branch --title "New Feature" --body "This is a new 
