name: Create a pull request

on:
  push

permissions:
  contents: write
  pull-requests: write

jobs:
  gh-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: philiprbrenan/ghAuth@main
        env:
          GH_TOKEN: ${{ secrets.CREATEPULLREQUEST }}                            # You will get: "message": "Bad credentials" unless you use a personal access token with at least repo scope.
